name: Infra Terraform

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - '.github/workflows/infra.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      TF_VAR_github_token: ${{ github.token }}

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v6

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve
