name: SonarQube

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonar:
    name: Analisis SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Instalar SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Analizar proyecto con SonarQube Cloud
        working-directory: FlightReservation.Api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"viccarretero_flightreservation" /o:"viccarretero-lab" /d:sonar.token="$SONAR_TOKEN" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build --no-incremental
          dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"